AWSTemplateFormatVersion: 2010-09-09
Description: A sample template
Resources:
  # 立ち上げたいリソースを定義していく
  # http://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html

  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: VPC
  
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
    Properties: 
      Tags:
        - Key: Name
          Value: SampleInternetGateway

  # InternetGateWayとVPCを関連付ける
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    DependsOn: InternetGateway
    Properties: 
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway
  
  # 踏み台サーバーを配備するサブネット
  PublicSubnet:
    Type: AWS::EC2::Subnet
    DependsOn: VPC
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: us-east-1a
      Tags:
      - Key: Name
        Value: publicSubnet
  
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: VPC
    Properties:
      VpcId:
        Ref: VPC
      Tags:
      - Key: Name
        Value: publicRouteTable
  
  # ルートテーブルにpublicサブネットへのルートを登録する
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: PublicRouteTable
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway

  # ルートテーブルとサブネットを関連付ける
  RouteToPublicSubnet:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: PublicRouteTable
    Properties: 
      RouteTableId: 
        Ref: PublicRouteTable
      SubnetId: 
        Ref: PublicSubnet
  
  # SSH接続を許可するセキュリティグループ
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DependsOn: VPC
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
  
  # 踏み台サーバーのEC2インスタンス
  # SSH接続に用いるKeyPairは予め用意しておく
  BastionInstance: 
    Type: AWS::EC2::Instance
    DependsOn: SSHSecurityGroup
    Properties: 
      InstanceType: t2.nano
      ImageId: ami-55ef662f
      KeyName: sampleSSH
      NetworkInterfaces: 
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:  
            - Ref: SSHSecurityGroup
            - Ref: PublicWebSecurityGroup
          SubnetId: 
            Ref: PublicSubnet
      Tags:
        - Key: Name
          Value: bastion

  # 踏み台サーバーにはElasticIPでアクセスする
  BastionInstanceEIP:
    Type: AWS::EC2::EIP
    DependsOn: BastionInstance
    Properties:
      Domain: vpc
      InstanceId: 
        Ref: BastionInstance
  
  # DB用サブネットはAZが異なるサブネットが最低2つ必要
  DatastoreSubnet1a: 
    Type: AWS::EC2::Subnet
    DependsOn: PrivateRouteTable
    Properties: 
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: us-east-1a
      Tags: 
        - Key: Name 
          Value: db-us-east-1a
      
  DatastoreSubnet1c: 
    Type: AWS::EC2::Subnet
    DependsOn: PrivateRouteTable
    Properties: 
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: us-east-1c
      Tags: 
        - Key: Name 
          Value: db-us-east-1c    

  DatastoreSubnet1aRouteTableAssociation: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: DatastoreSubnet1a
    Properties: 
      SubnetId:  
        Ref: DatastoreSubnet1a 
      RouteTableId:
        Ref: PrivateRouteTable

  DatastoreSubnet1cRouteTableAssociation: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: DatastoreSubnet1c
    Properties: 
      SubnetId:  
        Ref: DatastoreSubnet1c 
      RouteTableId:
        Ref: PrivateRouteTable
  
  # プライベートサブネット用のルートテーブル
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: VPC
    Properties:
      VpcId:
        Ref: VPC
      Tags:
      - Key: Name
        Value: privateRouteTable

  # インターネットからのhttp/httpsアクセスを許可する
  PublicWebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DependsOn: VPC
    Properties:
      GroupDescription: Enable access via internet gateway
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: TCP
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0
  
  # PublicWebSecurityGroupと踏み台からのアクセスを許可する
  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DependsOn: PublicWebSecurityGroup
    Properties:
      GroupDescription: Enable access via public security group
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 0
          ToPort: 65535
          SourceSecurityGroupId: 
            Ref: PublicWebSecurityGroup
        - IpProtocol: UDP
          FromPort: 0
          ToPort: 65535
          SourceSecurityGroupId: 
            Ref: PublicWebSecurityGroup
        - IpProtocol: ICMP
          FromPort: -1
          ToPort: -1
          SourceSecurityGroupId: 
            Ref: PublicWebSecurityGroup
  
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    DependsOn: PrivateRouteTable
    Properties:
      DBSubnetGroupDescription: Database subnets for RDS
      SubnetIds:
        - Ref: DatastoreSubnet1a
        - Ref: DatastoreSubnet1c
  
  MyDBParamGroup:
    Type: AWS::RDS::DBParameterGroup
    DependsOn: DBSubnetGroup
    Properties:
      Description: Default parameter group
      Family: MySQL5.6
      Parameters:
        character_set_database: utf8mb4
        character_set_client: utf8mb4
        character_set_connection: utf8mb4
        character_set_results: utf8mb4
        character_set_server: utf8mb4
        skip-character-set-client-handshake: true

  # MySQLインスタンス
  DbInstance: 
    Type: AWS::RDS::DBInstance
    DependsOn: DBSubnetGroup
    DeletionPolicy: Snapshot
    Properties: 
      Engine: MySQL
      EngineVersion: 5.6.37
      MultiAZ: false
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: sample
      DBName: sample_db
      MasterUsername: root
      MasterUserPassword: password
      DBParameterGroupName:
        Ref: MyDBParamGroup
      DBSubnetGroupName:
        Ref: DBSubnetGroup 
      VPCSecurityGroups:
        - Ref: PrivateSecurityGroup



      
    
