
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    DependsOn: PrivateRouteTable
    Properties:
      DBSubnetGroupDescription: Database subnets for RDS
      SubnetIds:
        - Ref: PrivateSubnetA
        - Ref: PrivateSubnetB
  
  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    DependsOn: DBSubnetGroup
    Properties:
      Description: Custom parameter group
      Family: MySQL5.6
      Parameters:
        character_set_database: utf8mb4
        character_set_client: utf8mb4
        character_set_connection: utf8mb4
        character_set_results: utf8mb4
        character_set_server: utf8mb4
        skip-character-set-client-handshake: true

  # MySQLインスタンス
  DbInstance: 
    Type: AWS::RDS::DBInstance
    DependsOn: DBSubnetGroup
    DeletionPolicy: Snapshot
    Properties: 
      Engine: MySQL
      EngineVersion: 5.6.37
      MultiAZ: false
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: sample
      DBName: sample_db
      MasterUsername: root
      MasterUserPassword: password
      DBParameterGroupName:
        Ref: DBParameterGroup
      DBSubnetGroupName:
        Ref: DBSubnetGroup 
      VPCSecurityGroups:
        - Ref: PrivateSecurityGroup

