###############################################################
# ネットワークの基礎部分と踏み台サーバーを us-east に構築する
# 事前に踏み台用のElastic IP Address、およびkeypairを用意しておくこと
###############################################################

AWSTemplateFormatVersion: 2010-09-09
Description: A sample template
Parameters:
  BastionEIPAllocationId:
    Description: EIP AllocationId for BastionInstance
    Type: String
  BastionKeypairName:
    Description: Keypair name for BastionInstance
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: VPC
  
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
    Properties: 
      Tags:
        - Key: Name
          Value: SampleInternetGateway

  # InternetGateWayとVPCを関連付ける
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    DependsOn: InternetGateway
    Properties: 
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway
  
  # publicサブネット用のルートテーブルを登録する
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: InternetGateway
    Properties:
      VpcId:
        Ref: VPC
      Tags:
      - Key: Name
        Value: publicRouteTable

  # InternetGatewayへのRoute
  IGWRoute:
    Type: AWS::EC2::Route
    DependsOn: PublicRouteTable
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway

  # InternetGateway経由でhttp/https接続を許可するサブネット
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    DependsOn: PublicRouteTable
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: us-east-1a
      Tags:
      - Key: Name
        Value: publicSubnetA

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    DependsOn: PublicRouteTable
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: us-east-1b
      Tags:
      - Key: Name
        Value: publicSubnetB

  RouteToPublicSubnetA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: PublicSubnetA
    Properties: 
      RouteTableId: 
        Ref: PublicRouteTable
      SubnetId: 
        Ref: PublicSubnetA

  RouteToPublicSubnetB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: PublicSubnetB
    Properties: 
      RouteTableId: 
        Ref: PublicRouteTable
      SubnetId: 
        Ref: PublicSubnetB

  # InternetGatewayからのhttp/httpsアクセスを許可するSGを作成
  HttpSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DependsOn: VPC
    Properties:
      GroupDescription: Enable access via internet gateway
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: TCP
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: HttpSecurityGroup

  # SSH接続を許可するセキュリティグループ
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DependsOn: VPC
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SSHSecurityGroup

  # Https/SSH接続を許可するセキュリティグループ
  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DependsOn: VPC
    Properties:
      GroupDescription: Enable access via HttpSecurityGroup
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: '80'
          ToPort: '80'
          SourceSecurityGroupId: 
            Ref: HttpSecurityGroup
        - IpProtocol: TCP
          FromPort: '443'
          ToPort: '443'
          SourceSecurityGroupId: 
            Ref: HttpSecurityGroup 
      Tags:
        - Key: Name
          Value: PublicSecurityGroup
          
  # 踏み台サーバーのEC2インスタンス
  # SSH接続に用いるKeyPairは予め用意しておく
  BastionInstance: 
    Type: AWS::EC2::Instance
    DependsOn: SSHSecurityGroup
    Properties: 
      InstanceType: t2.nano
      ImageId: ami-55ef662f
      KeyName: 
        Ref: BastionKeypairName
      NetworkInterfaces: 
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:  
            - Ref: SSHSecurityGroup
            - Ref: PublicSecurityGroup
          SubnetId: 
            Ref: PublicSubnetA
      Tags:
        - Key: Name
          Value: bastion
  
  # 予め用意していたEIPを踏み台のEC2に関連付ける
  BastionEIPAssociation:
    Type: "AWS::EC2::EIPAssociation"
    DependsOn: BastionInstance
    Properties:
      AllocationId: 
        Ref: BastionEIPAllocationId
      InstanceId: 
        Ref: BastionInstance
